# Main configuration file for credit fraud detection
data:
  raw_path: "../src/data/raw/creditcard.csv"
  processed_path: "../src/data/processed/"
  test_size: 0.2
  random_state: 42
  stratify: true

preprocessing:
  remove_duplicates: true
  scaling:
    method: "robust"  # robust, standard, minmax
    features: ["Amount", "Time"]
  
  sampling:
    method: "undersample"  # undersample, oversample, smote
    random_state: 42

features:
  target_column: "Class"
  drop_columns: []
  pca_features: ["V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10", 
                 "V11", "V12", "V13", "V14", "V15", "V16", "V17", "V18", "V19", 
                 "V20", "V21", "V22", "V23", "V24", "V25", "V26", "V27", "V28"]

models:
  logistic_regression:
    C: 0.01
    penalty: "l2"
    solver: "lbfgs"
    
  mlp:
    hidden_layer_sizes: [50, 50]
    max_iter: 1000
    random_state: 42
    
  xgboost:
    random_state: 42
    
  random_forest:
    n_estimators: 100
    random_state: 42
    
  svm:
    kernel: "rbf"
    C: 10

training:
  cv_folds: 5
  cv_shuffle: true
  cv_random_state: 42
  
hyperparameter_tuning:
  enabled: true
  cv_folds: 5
  
  logistic_regression:
    solver: ["liblinear"]
    
  svm:
    kernel: ["rbf", "linear"]
    C: [10, 15, 20]
    
  decision_tree:
    criterion: ["gini", "entropy"]
    
  random_forest:
    criterion: ["gini", "entropy"]
    n_estimators: [50, 100, 150]
    
  knn:
    n_neighbors: [5, 10, 15]

evaluation:
  metrics: ["accuracy", "f1_weighted", "precision", "recall", "roc_auc"]
  plot_confusion_matrix: true
  plot_roc_curve: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
tensorboard:
  log_dir: "experiments/tensorboard"
  enabled: true